<?xml version="1.0" encoding="utf-8"?>
<contentitemdata.kenticocommunity.qandaquestionpage>
  <ContentItemDataCommonDataID>
    <GUID>46b8cc1f-a997-4dab-9061-8ac12aaa6b5c</GUID>
    <ObjectType>cms.contentitemcommondata</ObjectType>
    <Parent>
      <CodeName>InvalidOperationException-The-connection-is-closed-when-building-solution-and-accessing-the-htsk4h4t</CodeName>
      <GUID>5dba739a-f71b-47c4-b9b6-062bf9979d80</GUID>
      <ObjectType>cms.contentitem</ObjectType>
    </Parent>
  </ContentItemDataCommonDataID>
  <ContentItemDataGUID>412dbc45-a857-4347-8b31-56d8432a4064</ContentItemDataGUID>
  <QAndAQuestionPageAcceptedAnswerDataGUID>c0195414-d563-4850-a66a-adf9b6c30288</QAndAQuestionPageAcceptedAnswerDataGUID>
  <QAndAQuestionPageAuthorMemberID>2</QAndAQuestionPageAuthorMemberID>
  <QAndAQuestionPageContent>
<![CDATA[
**Description:**\
We are encountering an `InvalidOperationException` with the message: "Invalid operation. The connection is closed." This occurs when trying to execute a database query. The issue first appears when building the solution and navigating to the localhost URL for the first time. After a short period and a few page refreshes, the error disappears and everything functions normally.

**How did it happen?**\
The error occurs every time we build our solution and access the localhost URL for the first time. The first time the page is accessed, we get the `InvalidOperationException` regarding the connection being closed. However, after waiting for a short period and refreshing the page a few times, the application behaves as expected without any issues.

**Steps to Reproduce the Issue:**

1. Build the solution.
2. Navigate to the localhost URL for the first time.
3. The page loads and the error `InvalidOperationException: The connection is closed` is thrown.
4. After a few moments and page refreshes, the issue resolves, and the application starts behaving as normal.

**Have you tried fixing it yourself? If you did, what steps did you take?**\
Yes, I have tried the following steps:

1. Checked the database connection initialization process.
2. Ensured that the connection is opened properly before executing commands.
3. Verified that connection pooling and async database operations are handled correctly.
4. Attempted to disable connection pooling to troubleshoot, but the issue still persists.

***

**Environment**

* Xperience by Kentico version: \[30.1.0]
* .NET version: \[8]
* Execution environment: local
]]>
  </QAndAQuestionPageContent>
  <QAndAQuestionPageDateCreated>2025-02-17 11:04:55Z</QAndAQuestionPageDateCreated>
  <QAndAQuestionPageDateModified>2025-02-17 11:06:02Z</QAndAQuestionPageDateModified>
  <QAndAQuestionPageDiscussionType>
    <![CDATA[[{"Identifier":"c50e7dd3-2b8e-47b5-96ee-3f04ccfde8b6"}]]]>
  </QAndAQuestionPageDiscussionType>
</contentitemdata.kenticocommunity.qandaquestionpage>